### PR TITLE
New fs base

### PR DESCRIPTION
**Pull request by Nhacsam**
Finally have a nice file structure using swig for templating and gulp for automatization.

### CODE REVIEW

**Comment by Gollwu** [comment]
Ok I'm installing node and postgre at work and I'll tell you about that during the day. We spoke on the filesystem much, I think it's okay :)

**Comment by Gollwu** [comment]
Yeah so I never did as much npm install my whole life... Mabe list all of them in the readme, that's quite annoying.

Still I'm getting this error on the gulp install-dev

"Task apidoc is not in your gulpfile"

Please advise me :)

Also need to update the readme as the sources now are in the folder "App"

**Comment by qr7hur** [comment]
With a good package.json that lists every dependency, you should need only one "npm install", am I wrong ?

**Comment by fabienDaou** [comment]
Djambi did like this if I am not mistaken

**Comment by fabienDaou** [comment]
omg sry dat close

omg noob

**Comment by Gollwu** [comment]
npm install did not install shit for me :)

**Comment by fabienDaou** [comment]
The only reason I can think of is that you did not npm install in the project

**Comment by Gollwu** [comment]
Well I do npm install on the main repo and it says that dependencies are missing... At one point I can't even download the dependencies (readable-stream/transform for example does not work on my local station and I'm stuck...)

**Comment by Nhacsam** [comment]
Try `npm install --dev`

**Comment by Nhacsam** [comment]
Changed my mind, don't do `npm install --dev`. Too long -.-"
`npm install` in the root directory should be enough. Tell me if you have other issue like this.

For apidoc, it's my bad. I removed the task in the commit b539c101d691e837636ebb3d1b14630d5ba98351 and didn't delete the dependency in the install-dev task. I fix it in a second

**Comment by Gollwu** [comment]
Yeah, even --dev changes nothing. And I'm on the root directory of course... Weird

**Comment by Nhacsam** [comment]
What is the output of `npm install` ? Of `npm -v` ?

apidoc issue is fixed by the way.

**Comment by Gollwu** [comment]
npm install gives 'images' errored after 65ms. Cannot find readable-stream/transform (whatever I already got this error with countless other dependency I installed them all it changed nothing and I can't install this one with npm install readable-stream/transform)

1.4.28 for my version. May be the problem indeed ? That's a good remark

**Comment by Nhacsam** [comment]
Continue in #47 to not flood this topic with your issue.

**Comment by Gollwu** [comment]
Ok Issued solved, I ran everything and the tests are ok. My database is filled with the fixtures. Good job :)

**Pull request merged**
